### ISSUE TITLE
How to learn a new programming language

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#221] opened 2023-01-04 17:42 UTC
I'm often asked this question, so here's some guidelines all in one place:

1. Find the official language documentation. It will be up to date.
2. Be leery of the top search engine results. They are old and have gamed the system. This isn't true all of the time, but keep your eye open for it.
3. Consider asking one of the AI systems for a bespoke example in your new language. The example might not be 100% correct, but it will likely point you in the right direction
4. Pick a project you have done in the past and port it to your new programming language (NES Emulator, Game of Life Simulator, Mandelbrot browser)
5. Look to Coding puzzle websites like Project Euler and Advent of Code

**Comment by jmarrec** [comment] 2023-01-05 09:57
duplicate of #213 ?

**Comment by lefticus** [comment] 2023-01-05 23:19
Yeah... thanks, I just noticed that @jmarrec it's terrible I keep duplicating myself...

**Closed** 2023-01-05 23:26 UTC
Labels: episode idea, C++ Weekly, ready to record
