### ISSUE TITLE
Type casting vs (what-is-it-called?)-{}-Initialization

### ISSUE THREAD

**Issue by stefanos82** [lefticus/cpp_weekly#162] opened 2022-09-24 21:20 UTC
**Channel**

C++Weekly

**Topics**

Discussion about whether or not to choose `{}-initialization` versus well-known type casting methodologies.

**Length**

I guess between 10 to 13 minutes.

**Further info**

I have tested this via godbolt and got the following:

```c++
#include <iostream>
#include <string>
#include <typeinfo>
#include <type_traits>
#include <boost/core/demangle.hpp>

int main()
{
    const char * foo = "john doe";
    decltype(auto) name = (std::string)foo; // without the cast, of course will return `char const*`
    std::cout << boost::core::demangle(typeid(name).name()) << '\n';
    auto name2 = std::string{foo};
    std::cout << boost::core::demangle(typeid(name2).name()) << '\n';
}
```

Output:

```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
```

So the question is, should we stop using type casting and prefer `{}-initialization` whenever we need to cast to a specific type or not?

**Comment by lefticus** [comment] 2022-09-25 21:36
I will look into doing an episode on this, but you should be aware that the habit of doing `(type)value` is incredibly dangerous and could lead to undefined behavior in the cases where it becomes a `reinterpret_cast`

**Comment by lefticus** [comment] 2023-01-16 20:15
Marking as duplicate of #210 (even though that one came later) hopefully it fills out the details when it releases.

**Closed by lefticus** 2023-01-16 20:15 UTC
Labels: episode idea, C++ Weekly

**Comment by stefanos82** [comment] 2023-01-16 20:47
Cheers @lefticus :+1: 

By the way Jason, can you edit your `About` section and add your YouTube channel's URL? This way those who find this repository for the very first time, they will visit the link and find out what is all about.
