### ISSUE TITLE
C++20's coroutines

### ISSUE THREAD

**Issue by SSBjY-Dave** [lefticus/cpp_weekly#126] opened 2022-08-16 04:57 UTC
**Channel**
C++Weekly

**Topics**
- The basics of coroutines
- A basic example for co_yield and co_return
- When to use them instead of std::thread

**Length**
I think this topic deserves a longer video something like 15-20 minutes, something like:
- 5 mins - The basics of coroutines
- 7-10 mins - A basic example for co_yield and co_return
- 3-5 mins - When to use them instead of std::thread

**Comment by lefticus** [comment] 2022-08-16 15:51
Closing as duplicate of the #78

**Closed by lefticus** 2022-08-16 15:51 UTC
Labels: episode idea
